.PHONY: clean All

All:
	@echo "----------Building project:[ daytime - Debug ]----------"
	@cd "daytime" && "$(MAKE)" -f  "daytime.mk"
clean:
	@echo "----------Cleaning project:[ daytime - Debug ]----------"
	@cd "daytime" && "$(MAKE)" -f  "daytime.mk" clean
